# nombre de nuestro workflow, conjunto de tareas que se ejecutan
name: CI

# Para decirle en que eventos se van a ejecutar esas tareas
on:
  # En este caso se va a ejecutar cuando se haga un push en la rama main
  push:
    branches: [ "main" ]


  # Para ejecutar un workflow manualmente
  workflow_dispatch:
    

# Jobs son una serie de pasos que se ejecutan
jobs:
  # Tiene un job que se llama buid
  build:
    # Va a ejecutar una máquina de ubuntu temporal
    runs-on: ubuntu-latest
    #Variables de entorno
    env:
      platform: aws
      region: us-east-1
      acount: 12345678

    # Detallamos los pasos que necesitamos ejecutar
    steps:
      - name: "Mostrar mensaje"
        run: echo "Hola mundo"
      - name: "Mostrando variables de entorno"
        if: ${{env.platform == 'azure'}}
        run: |
          echo "Este es el valor de plataforma: ${{env.platform}}"
          echo "Valor de region: ${{env.region}}"
          echo "Este es el valor de region: ${{env.acount}}"
      - name: "Mostrando variables por defecto"
        run: |
          echo "Este es el valor de plataforma: ${{github.event}}"

        